//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9043
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
// 
namespace Calbee.WMS.Services.CoreService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICoreService", Namespace="http://tempuri.org/")]
    public partial class CoreService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CoreService() {
            this.Url = "http://43.229.78.24/WMSService/CoreService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICoreService/GetCurrentDateTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetCurrentDateTime(out System.DateTime GetCurrentDateTimeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GetCurrentDateTimeResultSpecified) {
            object[] results = this.Invoke("GetCurrentDateTime", new object[0]);
            GetCurrentDateTimeResult = ((System.DateTime)(results[0]));
            GetCurrentDateTimeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCurrentDateTime(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCurrentDateTime", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndGetCurrentDateTime(System.IAsyncResult asyncResult, out System.DateTime GetCurrentDateTimeResult, out bool GetCurrentDateTimeResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            GetCurrentDateTimeResult = ((System.DateTime)(results[0]));
            GetCurrentDateTimeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICoreService/GetProgramVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetProgramVersion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string programName) {
            object[] results = this.Invoke("GetProgramVersion", new object[] {
                        programName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetProgramVersion(string programName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetProgramVersion", new object[] {
                        programName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetProgramVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ICoreService/GetRunning", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRunning([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string runningType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string runnintCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string runningKey, bool updateRunning, [System.Xml.Serialization.XmlIgnoreAttribute()] bool updateRunningSpecified) {
            object[] results = this.Invoke("GetRunning", new object[] {
                        runningType,
                        runnintCode,
                        runningKey,
                        updateRunning,
                        updateRunningSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetRunning(string runningType, string runnintCode, string runningKey, bool updateRunning, bool updateRunningSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetRunning", new object[] {
                        runningType,
                        runnintCode,
                        runningKey,
                        updateRunning,
                        updateRunningSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetRunning(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
