//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9151.
// 
namespace Calbee.WMS.Services.MasterService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMasterService", Namespace="http://tempuri.org/")]
    public partial class MasterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MasterService() {
            this.Url = "http://43.229.78.24/WMSService/MasterService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetWarehouses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
        public Warehouse[] GetWarehouses([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehosuecode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehosuename) {
            object[] results = this.Invoke("GetWarehouses", new object[] {
                        warehosuecode,
                        warehosuename});
            return ((Warehouse[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWarehouses(string warehosuecode, string warehosuename, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWarehouses", new object[] {
                        warehosuecode,
                        warehosuename}, callback, asyncState);
        }
        
        /// <remarks/>
        public Warehouse[] EndGetWarehouses(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Warehouse[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetWarehousesUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
        public Warehouse[] GetWarehousesUser(int userId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool userIdSpecified) {
            object[] results = this.Invoke("GetWarehousesUser", new object[] {
                        userId,
                        userIdSpecified});
            return ((Warehouse[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWarehousesUser(int userId, bool userIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWarehousesUser", new object[] {
                        userId,
                        userIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public Warehouse[] EndGetWarehousesUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Warehouse[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Location GetLocation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouseCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationType) {
            object[] results = this.Invoke("GetLocation", new object[] {
                        warehouseCode,
                        locationCode,
                        locationName,
                        locationType});
            return ((Location)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLocation(string warehouseCode, string locationCode, string locationName, string locationType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLocation", new object[] {
                        warehouseCode,
                        locationCode,
                        locationName,
                        locationType}, callback, asyncState);
        }
        
        /// <remarks/>
        public Location EndGetLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Location)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetLocations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
        public Location[] GetLocations([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouseCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationCode, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationName, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string locationType) {
            object[] results = this.Invoke("GetLocations", new object[] {
                        warehouseCode,
                        locationCode,
                        locationName,
                        locationType});
            return ((Location[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetLocations(string warehouseCode, string locationCode, string locationName, string locationType, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetLocations", new object[] {
                        warehouseCode,
                        locationCode,
                        locationName,
                        locationType}, callback, asyncState);
        }
        
        /// <remarks/>
        public Location[] EndGetLocations(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Location[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetWarehousesUserLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetWarehousesUserLocation(int user_id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool user_idSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code) {
            object[] results = this.Invoke("GetWarehousesUserLocation", new object[] {
                        user_id,
                        user_idSpecified,
                        warehouse_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetWarehousesUserLocation(int user_id, bool user_idSpecified, string warehouse_code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetWarehousesUserLocation", new object[] {
                        user_id,
                        user_idSpecified,
                        warehouse_code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetWarehousesUserLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Item GetItem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemName) {
            object[] results = this.Invoke("GetItem", new object[] {
                        itemNumber,
                        itemName});
            return ((Item)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItem(string itemNumber, string itemName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItem", new object[] {
                        itemNumber,
                        itemName}, callback, asyncState);
        }
        
        /// <remarks/>
        public Item EndGetItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Item)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetItemUoms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
        public ItemUom[] GetItemUoms([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string itemName) {
            object[] results = this.Invoke("GetItemUoms", new object[] {
                        itemNumber,
                        itemName});
            return ((ItemUom[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetItemUoms(string itemNumber, string itemName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetItemUoms", new object[] {
                        itemNumber,
                        itemName}, callback, asyncState);
        }
        
        /// <remarks/>
        public ItemUom[] EndGetItemUoms(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ItemUom[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
        public tbc_Status[] GetStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type) {
            object[] results = this.Invoke("GetStatus", new object[] {
                        type});
            return ((tbc_Status[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStatus(string type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStatus", new object[] {
                        type}, callback, asyncState);
        }
        
        /// <remarks/>
        public tbc_Status[] EndGetStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((tbc_Status[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMasterService/GetStatusComboboxItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
        public ComboBoxItem[] GetStatusComboboxItem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type) {
            object[] results = this.Invoke("GetStatusComboboxItem", new object[] {
                        type});
            return ((ComboBoxItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStatusComboboxItem(string type, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStatusComboboxItem", new object[] {
                        type}, callback, asyncState);
        }
        
        /// <remarks/>
        public ComboBoxItem[] EndGetStatusComboboxItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ComboBoxItem[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
    public partial class Warehouse {
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private int plantIdField;
        
        private bool plantIdFieldSpecified;
        
        private string warehouseCodeField;
        
        private int warehouseIdField;
        
        private bool warehouseIdFieldSpecified;
        
        private string warehouseNameField;
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int PlantId {
            get {
                return this.plantIdField;
            }
            set {
                this.plantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlantIdSpecified {
            get {
                return this.plantIdFieldSpecified;
            }
            set {
                this.plantIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehouseCode {
            get {
                return this.warehouseCodeField;
            }
            set {
                this.warehouseCodeField = value;
            }
        }
        
        /// <remarks/>
        public int WarehouseId {
            get {
                return this.warehouseIdField;
            }
            set {
                this.warehouseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseIdSpecified {
            get {
                return this.warehouseIdFieldSpecified;
            }
            set {
                this.warehouseIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehouseName {
            get {
                return this.warehouseNameField;
            }
            set {
                this.warehouseNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
    public partial class ComboBoxItem {
        
        private string displayMemberField;
        
        private string valueMemberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayMember {
            get {
                return this.displayMemberField;
            }
            set {
                this.displayMemberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ValueMember {
            get {
                return this.valueMemberField;
            }
            set {
                this.valueMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
    public partial class tbc_Status {
        
        private string descriptionField;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private int sequenceField;
        
        private bool sequenceFieldSpecified;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusNameField;
        
        private string statusTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SequenceSpecified {
            get {
                return this.sequenceFieldSpecified;
            }
            set {
                this.sequenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
    public partial class ItemUom {
        
        private string barCodeField;
        
        private double conversionFactorField;
        
        private bool conversionFactorFieldSpecified;
        
        private System.Nullable<double> grossWeightField;
        
        private bool grossWeightFieldSpecified;
        
        private System.Nullable<double> heightField;
        
        private bool heightFieldSpecified;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private int itemUomIdField;
        
        private bool itemUomIdFieldSpecified;
        
        private System.Nullable<double> lengthField;
        
        private bool lengthFieldSpecified;
        
        private string pickingClassField;
        
        private System.Nullable<bool> pickingUomField;
        
        private bool pickingUomFieldSpecified;
        
        private bool primaryUomField;
        
        private bool primaryUomFieldSpecified;
        
        private string putawayClassField;
        
        private System.Nullable<bool> shippingUomField;
        
        private bool shippingUomFieldSpecified;
        
        private System.Nullable<double> tareWeightField;
        
        private bool tareWeightFieldSpecified;
        
        private string uomField;
        
        private string uomPromptField;
        
        private System.Nullable<double> weightField;
        
        private bool weightFieldSpecified;
        
        private System.Nullable<double> widthField;
        
        private bool widthFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public double ConversionFactor {
            get {
                return this.conversionFactorField;
            }
            set {
                this.conversionFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConversionFactorSpecified {
            get {
                return this.conversionFactorFieldSpecified;
            }
            set {
                this.conversionFactorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> GrossWeight {
            get {
                return this.grossWeightField;
            }
            set {
                this.grossWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GrossWeightSpecified {
            get {
                return this.grossWeightFieldSpecified;
            }
            set {
                this.grossWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ItemUomId {
            get {
                return this.itemUomIdField;
            }
            set {
                this.itemUomIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemUomIdSpecified {
            get {
                return this.itemUomIdFieldSpecified;
            }
            set {
                this.itemUomIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickingClass {
            get {
                return this.pickingClassField;
            }
            set {
                this.pickingClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> PickingUom {
            get {
                return this.pickingUomField;
            }
            set {
                this.pickingUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickingUomSpecified {
            get {
                return this.pickingUomFieldSpecified;
            }
            set {
                this.pickingUomFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PrimaryUom {
            get {
                return this.primaryUomField;
            }
            set {
                this.primaryUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimaryUomSpecified {
            get {
                return this.primaryUomFieldSpecified;
            }
            set {
                this.primaryUomFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PutawayClass {
            get {
                return this.putawayClassField;
            }
            set {
                this.putawayClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ShippingUom {
            get {
                return this.shippingUomField;
            }
            set {
                this.shippingUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShippingUomSpecified {
            get {
                return this.shippingUomFieldSpecified;
            }
            set {
                this.shippingUomFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TareWeight {
            get {
                return this.tareWeightField;
            }
            set {
                this.tareWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TareWeightSpecified {
            get {
                return this.tareWeightFieldSpecified;
            }
            set {
                this.tareWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UomPrompt {
            get {
                return this.uomPromptField;
            }
            set {
                this.uomPromptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
    public partial class Item {
        
        private string alternateItemNumberField;
        
        private int categoryIdField;
        
        private bool categoryIdFieldSpecified;
        
        private string colorField;
        
        private string cooField;
        
        private string crossRefUomField;
        
        private System.Nullable<int> daysToExpireField;
        
        private bool daysToExpireFieldSpecified;
        
        private string descriptionField;
        
        private bool expiryDateControlField;
        
        private bool expiryDateControlFieldSpecified;
        
        private string gradeField;
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private string itemNumberField;
        
        private bool lotControlField;
        
        private bool lotControlFieldSpecified;
        
        private string modelField;
        
        private bool serialControlField;
        
        private bool serialControlFieldSpecified;
        
        private string sizeField;
        
        private string styleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlternateItemNumber {
            get {
                return this.alternateItemNumberField;
            }
            set {
                this.alternateItemNumberField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategoryIdSpecified {
            get {
                return this.categoryIdFieldSpecified;
            }
            set {
                this.categoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Coo {
            get {
                return this.cooField;
            }
            set {
                this.cooField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CrossRefUom {
            get {
                return this.crossRefUomField;
            }
            set {
                this.crossRefUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DaysToExpire {
            get {
                return this.daysToExpireField;
            }
            set {
                this.daysToExpireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysToExpireSpecified {
            get {
                return this.daysToExpireFieldSpecified;
            }
            set {
                this.daysToExpireFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public bool ExpiryDateControl {
            get {
                return this.expiryDateControlField;
            }
            set {
                this.expiryDateControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateControlSpecified {
            get {
                return this.expiryDateControlFieldSpecified;
            }
            set {
                this.expiryDateControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool LotControl {
            get {
                return this.lotControlField;
            }
            set {
                this.lotControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LotControlSpecified {
            get {
                return this.lotControlFieldSpecified;
            }
            set {
                this.lotControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public bool SerialControl {
            get {
                return this.serialControlField;
            }
            set {
                this.serialControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerialControlSpecified {
            get {
                return this.serialControlFieldSpecified;
            }
            set {
                this.serialControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Master")]
    public partial class Location {
        
        private bool isActiveField;
        
        private bool isActiveFieldSpecified;
        
        private string locationCodeField;
        
        private int locationIdField;
        
        private bool locationIdFieldSpecified;
        
        private string locationNameField;
        
        private string locationTypeField;
        
        private bool lpnControlledField;
        
        private bool lpnControlledFieldSpecified;
        
        private System.Nullable<int> pickSequenceField;
        
        private bool pickSequenceFieldSpecified;
        
        private int warehouseIdField;
        
        private bool warehouseIdFieldSpecified;
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsActiveSpecified {
            get {
                return this.isActiveFieldSpecified;
            }
            set {
                this.isActiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationIdSpecified {
            get {
                return this.locationIdFieldSpecified;
            }
            set {
                this.locationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool LpnControlled {
            get {
                return this.lpnControlledField;
            }
            set {
                this.lpnControlledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LpnControlledSpecified {
            get {
                return this.lpnControlledFieldSpecified;
            }
            set {
                this.lpnControlledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PickSequence {
            get {
                return this.pickSequenceField;
            }
            set {
                this.pickSequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickSequenceSpecified {
            get {
                return this.pickSequenceFieldSpecified;
            }
            set {
                this.pickSequenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WarehouseId {
            get {
                return this.warehouseIdField;
            }
            set {
                this.warehouseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseIdSpecified {
            get {
                return this.warehouseIdFieldSpecified;
            }
            set {
                this.warehouseIdFieldSpecified = value;
            }
        }
    }
}
