//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9043
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
// 
namespace Calbee.WMS.Services.InboundService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IInboundService", Namespace="http://tempuri.org/")]
    public partial class InboundService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public InboundService() {
            this.Url = "http://43.229.78.24/WMSService/InboundService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InboundMaster GetInboundMaster([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number) {
            object[] results = this.Invoke("GetInboundMaster", new object[] {
                        warehouse_code,
                        order_number});
            return ((InboundMaster)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundMaster(string warehouse_code, string order_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundMaster", new object[] {
                        warehouse_code,
                        order_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public InboundMaster EndGetInboundMaster(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InboundMaster)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundMasters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
        public InboundMaster[] GetInboundMasters([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number) {
            object[] results = this.Invoke("GetInboundMasters", new object[] {
                        warehouse_code,
                        order_number});
            return ((InboundMaster[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundMasters(string warehouse_code, string order_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundMasters", new object[] {
                        warehouse_code,
                        order_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public InboundMaster[] EndGetInboundMasters(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InboundMaster[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
        public InboundDetail[] GetInboundDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInboundDetails", new object[] {
                        order_number,
                        warehouse_code,
                        lpn,
                        item_number});
            return ((InboundDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundDetails(string order_number, string warehouse_code, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundDetails", new object[] {
                        order_number,
                        warehouse_code,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public InboundDetail[] EndGetInboundDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InboundDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundLpnDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
        public InboundLpnDetail[] GetInboundLpnDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInboundLpnDetails", new object[] {
                        order_number,
                        warehouse_code,
                        lpn,
                        item_number});
            return ((InboundLpnDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundLpnDetails(string order_number, string warehouse_code, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundLpnDetails", new object[] {
                        order_number,
                        warehouse_code,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public InboundLpnDetail[] EndGetInboundLpnDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InboundLpnDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundReceiptHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
        public ReceiptHeader[] GetInboundReceiptHeader([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number) {
            object[] results = this.Invoke("GetInboundReceiptHeader", new object[] {
                        order_number});
            return ((ReceiptHeader[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundReceiptHeader(string order_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundReceiptHeader", new object[] {
                        order_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReceiptHeader[] EndGetInboundReceiptHeader(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReceiptHeader[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundReceiptDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
        public ReceiptDetail[] GetInboundReceiptDetails([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string receipt_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInboundReceiptDetails", new object[] {
                        order_number,
                        warehouse_code,
                        receipt_number,
                        item_number});
            return ((ReceiptDetail[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundReceiptDetails(string order_number, string warehouse_code, string receipt_number, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundReceiptDetails", new object[] {
                        order_number,
                        warehouse_code,
                        receipt_number,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReceiptDetail[] EndGetInboundReceiptDetails(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReceiptDetail[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GenerateReceiveNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
        public ComboBoxItem[] GenerateReceiveNumber([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string user_name) {
            object[] results = this.Invoke("GenerateReceiveNumber", new object[] {
                        warehouse_code,
                        order_number,
                        user_name});
            return ((ComboBoxItem[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateReceiveNumber(string warehouse_code, string order_number, string user_name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateReceiveNumber", new object[] {
                        warehouse_code,
                        order_number,
                        user_name}, callback, asyncState);
        }
        
        /// <remarks/>
        public ComboBoxItem[] EndGenerateReceiveNumber(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ComboBoxItem[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetReceiptSummary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReceiptPalletSummary GetReceiptSummary([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetReceiptSummary", new object[] {
                        warehouse_code,
                        order_number,
                        item_number});
            return ((ReceiptPalletSummary)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetReceiptSummary(string warehouse_code, string order_number, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReceiptSummary", new object[] {
                        warehouse_code,
                        order_number,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReceiptPalletSummary EndGetReceiptSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReceiptPalletSummary)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/GetInboundReceiptDetailSummary", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ReceiptSummary GetInboundReceiptDetailSummary([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string order_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInboundReceiptDetailSummary", new object[] {
                        warehouse_code,
                        order_number,
                        item_number});
            return ((ReceiptSummary)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInboundReceiptDetailSummary(string warehouse_code, string order_number, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInboundReceiptDetailSummary", new object[] {
                        warehouse_code,
                        order_number,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public ReceiptSummary EndGetInboundReceiptDetailSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ReceiptSummary)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInboundService/SetReceiveItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response SetReceiveItem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ReceiveItem receive_item) {
            object[] results = this.Invoke("SetReceiveItem", new object[] {
                        receive_item});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetReceiveItem(ReceiveItem receive_item, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetReceiveItem", new object[] {
                        receive_item}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndSetReceiveItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class InboundMaster {
        
        private System.Nullable<int> customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private System.Nullable<System.DateTime> expectedDeliveryDateField;
        
        private bool expectedDeliveryDateFieldSpecified;
        
        private long inboundOrderMasterIdField;
        
        private bool inboundOrderMasterIdFieldSpecified;
        
        private string inboundOrderNumberField;
        
        private System.DateTime orderDateField;
        
        private bool orderDateFieldSpecified;
        
        private string orderStatusField;
        
        private string orderTypeField;
        
        private System.Nullable<int> supplierIdField;
        
        private bool supplierIdFieldSpecified;
        
        private int warehouseIdField;
        
        private bool warehouseIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerIdSpecified {
            get {
                return this.customerIdFieldSpecified;
            }
            set {
                this.customerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpectedDeliveryDate {
            get {
                return this.expectedDeliveryDateField;
            }
            set {
                this.expectedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedDeliveryDateSpecified {
            get {
                return this.expectedDeliveryDateFieldSpecified;
            }
            set {
                this.expectedDeliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InboundOrderMasterId {
            get {
                return this.inboundOrderMasterIdField;
            }
            set {
                this.inboundOrderMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderMasterIdSpecified {
            get {
                return this.inboundOrderMasterIdFieldSpecified;
            }
            set {
                this.inboundOrderMasterIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InboundOrderNumber {
            get {
                return this.inboundOrderNumberField;
            }
            set {
                this.inboundOrderNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderDateSpecified {
            get {
                return this.orderDateFieldSpecified;
            }
            set {
                this.orderDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SupplierId {
            get {
                return this.supplierIdField;
            }
            set {
                this.supplierIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SupplierIdSpecified {
            get {
                return this.supplierIdFieldSpecified;
            }
            set {
                this.supplierIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int WarehouseId {
            get {
                return this.warehouseIdField;
            }
            set {
                this.warehouseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseIdSpecified {
            get {
                return this.warehouseIdFieldSpecified;
            }
            set {
                this.warehouseIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Responses")]
    public partial class Response {
        
        private string messageField;
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class ReceiveItem {
        
        private string deviceField;
        
        private string expiryDateField;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private string lPNField;
        
        private string locationField;
        
        private string lotNumberField;
        
        private string orderNumberField;
        
        private string parentLPNField;
        
        private string plantCodeField;
        
        private double quantityReceiveField;
        
        private bool quantityReceiveFieldSpecified;
        
        private string receiveByField;
        
        private string receiveDateField;
        
        private string receiveNumberField;
        
        private string serialNumberField;
        
        private string statusField;
        
        private string uomField;
        
        private string warehouseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LPN {
            get {
                return this.lPNField;
            }
            set {
                this.lPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentLPN {
            get {
                return this.parentLPNField;
            }
            set {
                this.parentLPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
            }
        }
        
        /// <remarks/>
        public double QuantityReceive {
            get {
                return this.quantityReceiveField;
            }
            set {
                this.quantityReceiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceiveSpecified {
            get {
                return this.quantityReceiveFieldSpecified;
            }
            set {
                this.quantityReceiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiveBy {
            get {
                return this.receiveByField;
            }
            set {
                this.receiveByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiveNumber {
            get {
                return this.receiveNumberField;
            }
            set {
                this.receiveNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehouseCode {
            get {
                return this.warehouseCodeField;
            }
            set {
                this.warehouseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class ReceiptSummary {
        
        private double quantityOrderField;
        
        private bool quantityOrderFieldSpecified;
        
        private System.Nullable<double> quantityReceivedField;
        
        private bool quantityReceivedFieldSpecified;
        
        /// <remarks/>
        public double QuantityOrder {
            get {
                return this.quantityOrderField;
            }
            set {
                this.quantityOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityOrderSpecified {
            get {
                return this.quantityOrderFieldSpecified;
            }
            set {
                this.quantityOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> QuantityReceived {
            get {
                return this.quantityReceivedField;
            }
            set {
                this.quantityReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceivedSpecified {
            get {
                return this.quantityReceivedFieldSpecified;
            }
            set {
                this.quantityReceivedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class ReceiptPalletSummary {
        
        private double palletPlanField;
        
        private bool palletPlanFieldSpecified;
        
        private System.Nullable<double> palletReceivedField;
        
        private bool palletReceivedFieldSpecified;
        
        private System.Nullable<double> totalBoxReceivedField;
        
        private bool totalBoxReceivedFieldSpecified;
        
        /// <remarks/>
        public double PalletPlan {
            get {
                return this.palletPlanField;
            }
            set {
                this.palletPlanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PalletPlanSpecified {
            get {
                return this.palletPlanFieldSpecified;
            }
            set {
                this.palletPlanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PalletReceived {
            get {
                return this.palletReceivedField;
            }
            set {
                this.palletReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PalletReceivedSpecified {
            get {
                return this.palletReceivedFieldSpecified;
            }
            set {
                this.palletReceivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> TotalBoxReceived {
            get {
                return this.totalBoxReceivedField;
            }
            set {
                this.totalBoxReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalBoxReceivedSpecified {
            get {
                return this.totalBoxReceivedFieldSpecified;
            }
            set {
                this.totalBoxReceivedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Common")]
    public partial class ComboBoxItem {
        
        private string displayMemberField;
        
        private string valueMemberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayMember {
            get {
                return this.displayMemberField;
            }
            set {
                this.displayMemberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ValueMember {
            get {
                return this.valueMemberField;
            }
            set {
                this.valueMemberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class ReceiptDetail {
        
        private string createByField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private long inboundOrderDetailIdField;
        
        private bool inboundOrderDetailIdFieldSpecified;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private int itemUomIdField;
        
        private bool itemUomIdFieldSpecified;
        
        private string location_ReceivedField;
        
        private string lotNumberField;
        
        private string lpnField;
        
        private string parentLpnField;
        
        private double quantityReceivedField;
        
        private bool quantityReceivedFieldSpecified;
        
        private long receiptDetailIdField;
        
        private bool receiptDetailIdFieldSpecified;
        
        private long receiptHeaderIdField;
        
        private bool receiptHeaderIdFieldSpecified;
        
        private string receipt_Item_StatusField;
        
        private string remarkField;
        
        private string serialNumberField;
        
        private string statusField;
        
        private string uomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreateDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InboundOrderDetailId {
            get {
                return this.inboundOrderDetailIdField;
            }
            set {
                this.inboundOrderDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderDetailIdSpecified {
            get {
                return this.inboundOrderDetailIdFieldSpecified;
            }
            set {
                this.inboundOrderDetailIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        public int ItemUomId {
            get {
                return this.itemUomIdField;
            }
            set {
                this.itemUomIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemUomIdSpecified {
            get {
                return this.itemUomIdFieldSpecified;
            }
            set {
                this.itemUomIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location_Received {
            get {
                return this.location_ReceivedField;
            }
            set {
                this.location_ReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lpn {
            get {
                return this.lpnField;
            }
            set {
                this.lpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentLpn {
            get {
                return this.parentLpnField;
            }
            set {
                this.parentLpnField = value;
            }
        }
        
        /// <remarks/>
        public double QuantityReceived {
            get {
                return this.quantityReceivedField;
            }
            set {
                this.quantityReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceivedSpecified {
            get {
                return this.quantityReceivedFieldSpecified;
            }
            set {
                this.quantityReceivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long ReceiptDetailId {
            get {
                return this.receiptDetailIdField;
            }
            set {
                this.receiptDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptDetailIdSpecified {
            get {
                return this.receiptDetailIdFieldSpecified;
            }
            set {
                this.receiptDetailIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long ReceiptHeaderId {
            get {
                return this.receiptHeaderIdField;
            }
            set {
                this.receiptHeaderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptHeaderIdSpecified {
            get {
                return this.receiptHeaderIdFieldSpecified;
            }
            set {
                this.receiptHeaderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Receipt_Item_Status {
            get {
                return this.receipt_Item_StatusField;
            }
            set {
                this.receipt_Item_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class ReceiptHeader {
        
        private long inboundOrderMasterIdField;
        
        private bool inboundOrderMasterIdFieldSpecified;
        
        private string orderNumberField;
        
        private string orderStatusField;
        
        private string orderTypeField;
        
        private long receiptHeaderIdField;
        
        private bool receiptHeaderIdFieldSpecified;
        
        private string receiptNumberField;
        
        private string receiptStatusField;
        
        /// <remarks/>
        public long InboundOrderMasterId {
            get {
                return this.inboundOrderMasterIdField;
            }
            set {
                this.inboundOrderMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderMasterIdSpecified {
            get {
                return this.inboundOrderMasterIdFieldSpecified;
            }
            set {
                this.inboundOrderMasterIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        public long ReceiptHeaderId {
            get {
                return this.receiptHeaderIdField;
            }
            set {
                this.receiptHeaderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptHeaderIdSpecified {
            get {
                return this.receiptHeaderIdFieldSpecified;
            }
            set {
                this.receiptHeaderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiptStatus {
            get {
                return this.receiptStatusField;
            }
            set {
                this.receiptStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class InboundLpnDetail {
        
        private string boxNumberField;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private long inboundLpnDetailIdField;
        
        private bool inboundLpnDetailIdFieldSpecified;
        
        private long inboundOrderDetailIdField;
        
        private bool inboundOrderDetailIdFieldSpecified;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private string lotNumberField;
        
        private string lpnField;
        
        private string lpnStatusField;
        
        private System.Nullable<System.DateTime> productionDateField;
        
        private bool productionDateFieldSpecified;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private System.Nullable<double> quantityOrderField;
        
        private bool quantityOrderFieldSpecified;
        
        private System.Nullable<double> quantityReceiveField;
        
        private bool quantityReceiveFieldSpecified;
        
        private System.Nullable<double> quantityReceivedField;
        
        private bool quantityReceivedFieldSpecified;
        
        private string receiveByField;
        
        private System.Nullable<System.DateTime> receiveDateField;
        
        private bool receiveDateFieldSpecified;
        
        private string serialNumberField;
        
        private string uomField;
        
        private System.Nullable<double> weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BoxNumber {
            get {
                return this.boxNumberField;
            }
            set {
                this.boxNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InboundLpnDetailId {
            get {
                return this.inboundLpnDetailIdField;
            }
            set {
                this.inboundLpnDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundLpnDetailIdSpecified {
            get {
                return this.inboundLpnDetailIdFieldSpecified;
            }
            set {
                this.inboundLpnDetailIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InboundOrderDetailId {
            get {
                return this.inboundOrderDetailIdField;
            }
            set {
                this.inboundOrderDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderDetailIdSpecified {
            get {
                return this.inboundOrderDetailIdFieldSpecified;
            }
            set {
                this.inboundOrderDetailIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lpn {
            get {
                return this.lpnField;
            }
            set {
                this.lpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LpnStatus {
            get {
                return this.lpnStatusField;
            }
            set {
                this.lpnStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ProductionDate {
            get {
                return this.productionDateField;
            }
            set {
                this.productionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductionDateSpecified {
            get {
                return this.productionDateFieldSpecified;
            }
            set {
                this.productionDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> QuantityOrder {
            get {
                return this.quantityOrderField;
            }
            set {
                this.quantityOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityOrderSpecified {
            get {
                return this.quantityOrderFieldSpecified;
            }
            set {
                this.quantityOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> QuantityReceive {
            get {
                return this.quantityReceiveField;
            }
            set {
                this.quantityReceiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceiveSpecified {
            get {
                return this.quantityReceiveFieldSpecified;
            }
            set {
                this.quantityReceiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> QuantityReceived {
            get {
                return this.quantityReceivedField;
            }
            set {
                this.quantityReceivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceivedSpecified {
            get {
                return this.quantityReceivedFieldSpecified;
            }
            set {
                this.quantityReceivedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReceiveBy {
            get {
                return this.receiveByField;
            }
            set {
                this.receiveByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiveDateSpecified {
            get {
                return this.receiveDateFieldSpecified;
            }
            set {
                this.receiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inbound")]
    public partial class InboundDetail {
        
        private string alternateItemNumberField;
        
        private string crossRefUomField;
        
        private System.Nullable<int> daysToExpireField;
        
        private bool daysToExpireFieldSpecified;
        
        private string defaultItemStatusField;
        
        private string defaultLPNField;
        
        private string defaultLocationField;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private bool expiryDateControlField;
        
        private bool expiryDateControlFieldSpecified;
        
        private string gradeField;
        
        private InboundLpnDetail[] inboundLpnDetailsField;
        
        private long inboundOrderDetailIdField;
        
        private bool inboundOrderDetailIdFieldSpecified;
        
        private long inboundOrderMasterIdField;
        
        private bool inboundOrderMasterIdFieldSpecified;
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private string itemStatusField;
        
        private int itemUomIdField;
        
        private bool itemUomIdFieldSpecified;
        
        private string lineNumberField;
        
        private bool lotControlField;
        
        private bool lotControlFieldSpecified;
        
        private string lotNumberField;
        
        private bool lpnControlField;
        
        private bool lpnControlFieldSpecified;
        
        private double quantityOrderField;
        
        private bool quantityOrderFieldSpecified;
        
        private double quantityReceiveField;
        
        private bool quantityReceiveFieldSpecified;
        
        private bool serialControlField;
        
        private bool serialControlFieldSpecified;
        
        private string uomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlternateItemNumber {
            get {
                return this.alternateItemNumberField;
            }
            set {
                this.alternateItemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CrossRefUom {
            get {
                return this.crossRefUomField;
            }
            set {
                this.crossRefUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> DaysToExpire {
            get {
                return this.daysToExpireField;
            }
            set {
                this.daysToExpireField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DaysToExpireSpecified {
            get {
                return this.daysToExpireFieldSpecified;
            }
            set {
                this.daysToExpireFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DefaultItemStatus {
            get {
                return this.defaultItemStatusField;
            }
            set {
                this.defaultItemStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DefaultLPN {
            get {
                return this.defaultLPNField;
            }
            set {
                this.defaultLPNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DefaultLocation {
            get {
                return this.defaultLocationField;
            }
            set {
                this.defaultLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ExpiryDateControl {
            get {
                return this.expiryDateControlField;
            }
            set {
                this.expiryDateControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateControlSpecified {
            get {
                return this.expiryDateControlFieldSpecified;
            }
            set {
                this.expiryDateControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public InboundLpnDetail[] InboundLpnDetails {
            get {
                return this.inboundLpnDetailsField;
            }
            set {
                this.inboundLpnDetailsField = value;
            }
        }
        
        /// <remarks/>
        public long InboundOrderDetailId {
            get {
                return this.inboundOrderDetailIdField;
            }
            set {
                this.inboundOrderDetailIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderDetailIdSpecified {
            get {
                return this.inboundOrderDetailIdFieldSpecified;
            }
            set {
                this.inboundOrderDetailIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InboundOrderMasterId {
            get {
                return this.inboundOrderMasterIdField;
            }
            set {
                this.inboundOrderMasterIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InboundOrderMasterIdSpecified {
            get {
                return this.inboundOrderMasterIdFieldSpecified;
            }
            set {
                this.inboundOrderMasterIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemStatus {
            get {
                return this.itemStatusField;
            }
            set {
                this.itemStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ItemUomId {
            get {
                return this.itemUomIdField;
            }
            set {
                this.itemUomIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemUomIdSpecified {
            get {
                return this.itemUomIdFieldSpecified;
            }
            set {
                this.itemUomIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool LotControl {
            get {
                return this.lotControlField;
            }
            set {
                this.lotControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LotControlSpecified {
            get {
                return this.lotControlFieldSpecified;
            }
            set {
                this.lotControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool LpnControl {
            get {
                return this.lpnControlField;
            }
            set {
                this.lpnControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LpnControlSpecified {
            get {
                return this.lpnControlFieldSpecified;
            }
            set {
                this.lpnControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double QuantityOrder {
            get {
                return this.quantityOrderField;
            }
            set {
                this.quantityOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityOrderSpecified {
            get {
                return this.quantityOrderFieldSpecified;
            }
            set {
                this.quantityOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double QuantityReceive {
            get {
                return this.quantityReceiveField;
            }
            set {
                this.quantityReceiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityReceiveSpecified {
            get {
                return this.quantityReceiveFieldSpecified;
            }
            set {
                this.quantityReceiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SerialControl {
            get {
                return this.serialControlField;
            }
            set {
                this.serialControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerialControlSpecified {
            get {
                return this.serialControlFieldSpecified;
            }
            set {
                this.serialControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
    }
}
