//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9043
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9043.
// 
namespace Calbee.WMS.Services.InventoryService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IInventoryService", Namespace="http://tempuri.org/")]
    public partial class InventoryService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public InventoryService() {
            this.Url = "http://43.229.78.24/WMSService/InventoryService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Inventory GetInventory([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInventory", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number});
            return ((Inventory)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventory(string warehouse_code, string location_code, string parent_lpn, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventory", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public Inventory EndGetInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Inventory)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventorys", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inventory")]
        public Inventory[] GetInventorys([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lot_number) {
            object[] results = this.Invoke("GetInventorys", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number,
                        lot_number});
            return ((Inventory[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventorys(string warehouse_code, string location_code, string parent_lpn, string lpn, string item_number, string lot_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventorys", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number,
                        lot_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public Inventory[] EndGetInventorys(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Inventory[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryFilters", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inventory")]
        public Inventory[] GetInventoryFilters([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string filter) {
            object[] results = this.Invoke("GetInventoryFilters", new object[] {
                        warehouse_code,
                        filter});
            return ((Inventory[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryFilters(string warehouse_code, string filter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryFilters", new object[] {
                        warehouse_code,
                        filter}, callback, asyncState);
        }
        
        /// <remarks/>
        public Inventory[] EndGetInventoryFilters(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Inventory[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryLpns", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetInventoryLpns([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn) {
            object[] results = this.Invoke("GetInventoryLpns", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryLpns(string warehouse_code, string location_code, string parent_lpn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryLpns", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInventoryLpns(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryItemNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetInventoryItemNumbers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn) {
            object[] results = this.Invoke("GetInventoryItemNumbers", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryItemNumbers(string warehouse_code, string location_code, string parent_lpn, string lpn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryItemNumbers", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInventoryItemNumbers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryLotNumbers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetInventoryLotNumbers([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInventoryLotNumbers", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryLotNumbers(string warehouse_code, string location_code, string parent_lpn, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryLotNumbers", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInventoryLotNumbers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryExpiryDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetInventoryExpiryDates([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInventoryExpiryDates", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryExpiryDates(string warehouse_code, string location_code, string parent_lpn, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryExpiryDates", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInventoryExpiryDates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetInventoryStatuss", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] GetInventoryStatuss([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parent_lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string lpn, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string item_number) {
            object[] results = this.Invoke("GetInventoryStatuss", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetInventoryStatuss(string warehouse_code, string location_code, string parent_lpn, string lpn, string item_number, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetInventoryStatuss", new object[] {
                        warehouse_code,
                        location_code,
                        parent_lpn,
                        lpn,
                        item_number}, callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndGetInventoryStatuss(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/GetSuggestLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetSuggestLocation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string warehouse_code, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string location_code) {
            object[] results = this.Invoke("GetSuggestLocation", new object[] {
                        warehouse_code,
                        location_code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSuggestLocation(string warehouse_code, string location_code, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSuggestLocation", new object[] {
                        warehouse_code,
                        location_code}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetSuggestLocation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInventoryService/SetPickupPutawayItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Response SetPickupPutawayItem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] InventoryItem item) {
            object[] results = this.Invoke("SetPickupPutawayItem", new object[] {
                        item});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetPickupPutawayItem(InventoryItem item, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetPickupPutawayItem", new object[] {
                        item}, callback, asyncState);
        }
        
        /// <remarks/>
        public Response EndSetPickupPutawayItem(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Response)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inventory")]
    public partial class Inventory {
        
        private string alternateItemNumberField;
        
        private string crossRefUomField;
        
        private System.Nullable<System.DateTime> expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private bool expiryDateControlField;
        
        private bool expiryDateControlFieldSpecified;
        
        private long inventoryIdField;
        
        private bool inventoryIdFieldSpecified;
        
        private string inventoryTypeField;
        
        private int itemIdField;
        
        private bool itemIdFieldSpecified;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private string locationCodeField;
        
        private int locationIdField;
        
        private bool locationIdFieldSpecified;
        
        private string locationNameField;
        
        private bool lotControlField;
        
        private bool lotControlFieldSpecified;
        
        private string lotNumberField;
        
        private string lpnField;
        
        private bool lpnControlField;
        
        private bool lpnControlFieldSpecified;
        
        private string ownerCodeField;
        
        private System.Nullable<int> ownerIdField;
        
        private bool ownerIdFieldSpecified;
        
        private string parentLpnField;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private double quantityAllocatedField;
        
        private bool quantityAllocatedFieldSpecified;
        
        private System.DateTime receiveDateField;
        
        private bool receiveDateFieldSpecified;
        
        private bool serialControlField;
        
        private bool serialControlFieldSpecified;
        
        private string serialNumberField;
        
        private int statusIdField;
        
        private bool statusIdFieldSpecified;
        
        private string statusNameField;
        
        private string uOMField;
        
        private string warehosueCodeField;
        
        private string warehosueNameField;
        
        private int warehouseIdField;
        
        private bool warehouseIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AlternateItemNumber {
            get {
                return this.alternateItemNumberField;
            }
            set {
                this.alternateItemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CrossRefUom {
            get {
                return this.crossRefUomField;
            }
            set {
                this.crossRefUomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ExpiryDateControl {
            get {
                return this.expiryDateControlField;
            }
            set {
                this.expiryDateControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpiryDateControlSpecified {
            get {
                return this.expiryDateControlFieldSpecified;
            }
            set {
                this.expiryDateControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long InventoryId {
            get {
                return this.inventoryIdField;
            }
            set {
                this.inventoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryIdSpecified {
            get {
                return this.inventoryIdFieldSpecified;
            }
            set {
                this.inventoryIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string InventoryType {
            get {
                return this.inventoryTypeField;
            }
            set {
                this.inventoryTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemIdSpecified {
            get {
                return this.itemIdFieldSpecified;
            }
            set {
                this.itemIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationIdSpecified {
            get {
                return this.locationIdFieldSpecified;
            }
            set {
                this.locationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public bool LotControl {
            get {
                return this.lotControlField;
            }
            set {
                this.lotControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LotControlSpecified {
            get {
                return this.lotControlFieldSpecified;
            }
            set {
                this.lotControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lpn {
            get {
                return this.lpnField;
            }
            set {
                this.lpnField = value;
            }
        }
        
        /// <remarks/>
        public bool LpnControl {
            get {
                return this.lpnControlField;
            }
            set {
                this.lpnControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LpnControlSpecified {
            get {
                return this.lpnControlFieldSpecified;
            }
            set {
                this.lpnControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OwnerCode {
            get {
                return this.ownerCodeField;
            }
            set {
                this.ownerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> OwnerId {
            get {
                return this.ownerIdField;
            }
            set {
                this.ownerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OwnerIdSpecified {
            get {
                return this.ownerIdFieldSpecified;
            }
            set {
                this.ownerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentLpn {
            get {
                return this.parentLpnField;
            }
            set {
                this.parentLpnField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double QuantityAllocated {
            get {
                return this.quantityAllocatedField;
            }
            set {
                this.quantityAllocatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityAllocatedSpecified {
            get {
                return this.quantityAllocatedFieldSpecified;
            }
            set {
                this.quantityAllocatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceiveDate {
            get {
                return this.receiveDateField;
            }
            set {
                this.receiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiveDateSpecified {
            get {
                return this.receiveDateFieldSpecified;
            }
            set {
                this.receiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SerialControl {
            get {
                return this.serialControlField;
            }
            set {
                this.serialControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SerialControlSpecified {
            get {
                return this.serialControlFieldSpecified;
            }
            set {
                this.serialControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusIdSpecified {
            get {
                return this.statusIdFieldSpecified;
            }
            set {
                this.statusIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehosueCode {
            get {
                return this.warehosueCodeField;
            }
            set {
                this.warehosueCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehosueName {
            get {
                return this.warehosueNameField;
            }
            set {
                this.warehosueNameField = value;
            }
        }
        
        /// <remarks/>
        public int WarehouseId {
            get {
                return this.warehouseIdField;
            }
            set {
                this.warehouseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarehouseIdSpecified {
            get {
                return this.warehouseIdFieldSpecified;
            }
            set {
                this.warehouseIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Responses")]
    public partial class Response {
        
        private string messageField;
        
        private int statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WMS.Service.Models.Transaction.Inventory")]
    public partial class InventoryItem {
        
        private bool allExpField;
        
        private bool allExpFieldSpecified;
        
        private bool allItemField;
        
        private bool allItemFieldSpecified;
        
        private bool allLotField;
        
        private bool allLotFieldSpecified;
        
        private bool allLpnField;
        
        private bool allLpnFieldSpecified;
        
        private string deviceField;
        
        private string expiryDateField;
        
        private string itemNameField;
        
        private string itemNumberField;
        
        private string locationField;
        
        private string lotNumberField;
        
        private string lpnField;
        
        private string ownerCodeField;
        
        private string parentLpnField;
        
        private string pickByField;
        
        private System.DateTime pickDateField;
        
        private bool pickDateFieldSpecified;
        
        private string plantCodeField;
        
        private double quantityField;
        
        private bool quantityFieldSpecified;
        
        private string serialNumberField;
        
        private string statusField;
        
        private string subTranTypeField;
        
        private string toLocationField;
        
        private string toLotNumberField;
        
        private string toLpnField;
        
        private string toParentLpnField;
        
        private string toStatusField;
        
        private string transactionTypeField;
        
        private string uomField;
        
        private string warehouseCodeField;
        
        /// <remarks/>
        public bool AllExp {
            get {
                return this.allExpField;
            }
            set {
                this.allExpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllExpSpecified {
            get {
                return this.allExpFieldSpecified;
            }
            set {
                this.allExpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllItem {
            get {
                return this.allItemField;
            }
            set {
                this.allItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllItemSpecified {
            get {
                return this.allItemFieldSpecified;
            }
            set {
                this.allItemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllLot {
            get {
                return this.allLotField;
            }
            set {
                this.allLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllLotSpecified {
            get {
                return this.allLotFieldSpecified;
            }
            set {
                this.allLotFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllLpn {
            get {
                return this.allLpnField;
            }
            set {
                this.allLpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllLpnSpecified {
            get {
                return this.allLpnFieldSpecified;
            }
            set {
                this.allLpnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Device {
            get {
                return this.deviceField;
            }
            set {
                this.deviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lpn {
            get {
                return this.lpnField;
            }
            set {
                this.lpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OwnerCode {
            get {
                return this.ownerCodeField;
            }
            set {
                this.ownerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParentLpn {
            get {
                return this.parentLpnField;
            }
            set {
                this.parentLpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickBy {
            get {
                return this.pickByField;
            }
            set {
                this.pickByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PickDate {
            get {
                return this.pickDateField;
            }
            set {
                this.pickDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickDateSpecified {
            get {
                return this.pickDateFieldSpecified;
            }
            set {
                this.pickDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PlantCode {
            get {
                return this.plantCodeField;
            }
            set {
                this.plantCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SerialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SubTranType {
            get {
                return this.subTranTypeField;
            }
            set {
                this.subTranTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToLocation {
            get {
                return this.toLocationField;
            }
            set {
                this.toLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToLotNumber {
            get {
                return this.toLotNumberField;
            }
            set {
                this.toLotNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToLpn {
            get {
                return this.toLpnField;
            }
            set {
                this.toLpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToParentLpn {
            get {
                return this.toParentLpnField;
            }
            set {
                this.toParentLpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ToStatus {
            get {
                return this.toStatusField;
            }
            set {
                this.toStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WarehouseCode {
            get {
                return this.warehouseCodeField;
            }
            set {
                this.warehouseCodeField = value;
            }
        }
    }
}
